### ISSUE TITLE
Install the Bosch PlugIn on Home Assistant

### ISSUE THREAD

**Issue by bitdevil007** [cabrust/bshlocal-home-assistant#1]
Hi,
i have running a raspbarryPi with homeassitant.
But how do i install the Bosch PlugIn?
I have copy the files on my homeassistent in
costum_components/bshlocal
But what must i write in the configuration.yaml ?
And Where can i find the access cert and access key ?

I Hope you can help me.

**Comment by cabrust** [comment]
Hi bitdevil007,

you can create a self-signed client cert with openssl, just like you would for any https client connection. You then have to register it, using the password you set in the app. Follow the instructions [here](https://github.com/BoschSmartHome/bosch-shc-api-docs/tree/master/postman#register-a-new-client-to-the-bosch-smart-home-controller) in Postman.

The config then should look like this:
```
bshlocal:
    key: my.key
    certificate: my.certificate
    ip_address: 192.168.2.whatever your SHC's ip address is
```

Sadly, there hasn't been much progress with the plugin, but this should work for the moment.
